# Generated by Django 5.2.6 on 2025-10-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='slag',
            new_name='slug',
        ),
    ]
